SELECT 
    {segment} AS SEGMENT
    , SUM(tb.TOTAL_AMOUNT_GROSS) AS TOTAL_AMOUNT_GROSS 
    , SUM(tb.TOTAL_TRADING_PROFIT_NET) AS TOTAL_TRADING_PROFIT_NET
FROM 
    CORE_PROD.DATAMART_GKK.TRANSACTIONBON_FACT_STD_GKK tb
LEFT JOIN  
    CORE_PROD.DATAMART_GKK.CUSTOMER_DIM_STD_GKK c --ALL customers
ON
    tb.CUSTOMERID = c.CUSTOMERID
WHERE 
    tb.PURCHASE_DT BETWEEN :start_date AND :end_date
GROUP BY ALL;